### ISSUE TITLE
pyOFM build issue on HPC

### ISSUE THREAD

**Issue by uttamcadambi07** [mdolab/pyofm#10]
## Description
Issue with building.

Command: make

Output:

make
```
(cd src && python setup.py build_ext --inplace)
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    ext_modules=cythonize(ext, language_level=3),
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 977, in cythonize
    aliases=aliases)
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 857, in create_extension_list
    m, metadata = create_extension(template, kwds)
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 739, in default_create_extension
    depends = resolve_depends(kwds['depends'], include_dirs)
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 448, in resolve_depends
    path = resolve_depend(depend, include_dirs)
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Utils.py", line 41, in wrapper
    res = cache[args] = f(*args)
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 459, in resolve_depend
    path = join_path(dir, depend)
  File "/home/ucp1n22/.local/lib/python3.7/site-packages/Cython/Utils.py", line 41, in wrapper
    res = cache[args] = f(*args)
  File "/local/software/python/3.7.3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
make: *** [default] Error 1
```
Modules loaded:
```
Currently Loaded Modules:
  1) git/2.24.1   2) intel-compilers/18.0.3   3) libfabric/1.7.0   4) gcc/6.4.0   5) boost/1.70.0   6) petsc/3.11   7) python/3.7.3   8) intel-mpi/2018.3.222
```
Please can you advise on how this error can be fixed?

**Comment by friedenhe** [comment]
Check the response on DAFoam discussion
